### PR TITLE
Merge Fan's updates and fixes with the mother repo

### PR DESCRIPTION
**Pull request by fanbu1995**

### CODE REVIEW

**Comment by schuemie** [comment]
Thanks @fanbu1995 ! This is great work, and sorry you had to clean up my mess.

Should this be merged into main? We have papers that point to this repo, so we probably should make sure to have a representation of the code executed for those papers. But we could solve that with different git tags. What do you think?

**Comment by fanbu1995** [comment]
@schuemie Great point re: merging this to `main` for better code dissemination. I postponed a little on that, because @shounakch is also working on combining the concurrent comparator design into Eumaeus. 

**So for now, can we use a different git tag somehow?** Eventually we may want to merge all updates into `main`.

**Comment by schuemie** [comment]
Yes, you can just keep using a branch like you are doing now (develop), although you could create your own branch with a more meaningful name if you want. A tag is for a very specific state of the repo, so if you want to keep making changes a branch is better for now.

**Comment by fanbu1995** [comment]
> Yes, you can just keep using a branch like you are doing now (develop), although you could create your own branch with a more meaningful name if you want. A tag is for a very specific state of the repo, so if you want to keep making changes a branch is better for now.

Sounds great to me. Thank you, Martijn! I think this will soon become part of the current comparator branch; and then I can merge it into main and update the version number as well.

**Pull request merged**
